#!/usr/bin/env bash
# Set the wallpaper on both monitors — applies immediately AND persists.
#   setbg.sh ~/Pictures/wall.png
set -euo pipefail

IMG="${1:-}"
if [ -z "$IMG" ]; then
    echo "usage: setbg.sh /path/to/image.(png|jpg|jpeg|webp)"
    exit 1
fi
IMG="$(readlink -f "$IMG")"
[ -r "$IMG" ] || { echo "cannot read: $IMG"; exit 1; }

CONF="$HOME/.config/hypr/hyprpaper.conf"

# apply live via hyprpaper's IPC
if pgrep -x hyprpaper >/dev/null; then
    hyprctl hyprpaper unload all      >/dev/null || true
    hyprctl hyprpaper preload "$IMG"  >/dev/null
    hyprctl hyprpaper wallpaper ",$IMG" >/dev/null   # empty monitor = all monitors
else
    echo "note: hyprpaper isn't running; config written, will apply next login"
fi

# persist for next login
cat > "$CONF" <<CONFEOF
# Wallpaper — generated by ~/.config/hypr/scripts/setbg.sh
preload = $IMG

wallpaper = HDMI-A-2, $IMG
wallpaper = HDMI-A-1, $IMG

splash = false
ipc = on
CONFEOF

echo "wallpaper set: $IMG"
