backend = "xrender";
vsync = true;
shadow = true;
shadow-radius = 16;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.3;
corner-radius = 12;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = true;

fading = true;
fade-delta = 5;

animations = true;
animation-stiffness-in-tag = 300;
animation-dampening = 25;
animation-window-mass = 1.0;
animation-for-open-window = "slide-down";
animation-for-unmap-window = "slide-up";
animation-for-transient-window = "zoom";
animation-for-move-window = "slide";
animation-for-workspace-switch-in = "slide-left";
animation-for-workspace-switch-out = "slide-right";

size-transition = true;
